version: 0.2

env:
  parameter-store:
    JWT_SECRET: "/flask/jwt_secret"

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Build started on `date`
      - docker build -t flask-app --build-arg JWT_SECRET=$JWT_SECRET .
      - python -m unittest discover -s tests
      - docker tag flask-app:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-app:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/flask-app:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - kubectl apply -f kubernetes/deployment.yml
      - kubectl apply -f kubernetes/service.yml
